name: CI

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/cache@v1
        id: cache
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: NODE_ENV=dev yarn

      - name: Test project
        run: yarn && yarn test

      - name: Lint
        run: yarn lint

      - name: Tests
        run: yarn build && yarn jest

      - name: Coverage
        run: yarn codecov
